
CREATE TABLE IF NOT EXISTS ALLIANCE (
    ID INT,
    UPDATED DATETIME(9) NOT NULL,
    CONSTRAINT PK_Alliance PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ANSIBLEX (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    "ansiblexId" BIGINT NOT NULL,
    "allianceId" INT NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "solarSystemId" INT NOT NULL
);
ALTER TABLE ANSIBLEX ADD CONSTRAINT ANSIBLEX_ANSIBLEXID_ALLIANCEID_UNIQUE UNIQUE ("ansiblexId", "allianceId");

CREATE TABLE IF NOT EXISTS TEMPORARYCONNECTION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    "system1Id" INT NOT NULL,
    "system2Id" INT NOT NULL,
    "characterId" INT NOT NULL,
    "system1Name" VARCHAR(255) NOT NULL,
    "system2Name" VARCHAR(255) NOT NULL,
    CREATED DATETIME(9) NOT NULL
);
ALTER TABLE TEMPORARYCONNECTION ADD CONSTRAINT TEMPORARYCONNECTION_SYSTEM1ID_SYSTEM2ID_CHARACTERID_UNIQUE
    UNIQUE ("system1Id", "system2Id", "characterId");
