
ALTER TABLE ANSIBLEX RENAME TO ANSIBLEXV02;

CREATE TABLE IF NOT EXISTS ANSIBLEX (
    ID BIGINT,
    "NAME" VARCHAR(255) NOT NULL,
    "solarSystemId" INT NOT NULL,
    CONSTRAINT PK_Ansiblex PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ANSIBLEXALLIANCE (
    "ansiblexId" BIGINT,
    "allianceId" INT,
    CONSTRAINT PK_AnsiblexAlliance PRIMARY KEY ("ansiblexId", "allianceId"),
    CONSTRAINT FK_ANSIBLEXALLIANCE_ANSIBLEXID_ID FOREIGN KEY ("ansiblexId") REFERENCES ANSIBLEX(ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_ANSIBLEXALLIANCE_ALLIANCEID_ID FOREIGN KEY ("allianceId") REFERENCES ALLIANCE(ID)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- copy data

INSERT INTO ANSIBLEX (id, "NAME", "solarSystemId")
SELECT DISTINCT "ansiblexId", "NAME", "solarSystemId" FROM ANSIBLEXV02;

INSERT INTO ANSIBLEXALLIANCE ("ansiblexId", "allianceId")
SELECT "ansiblexId", "allianceId" FROM ANSIBLEXV02;

DROP TABLE ANSIBLEXV02;
