
CREATE TABLE IF NOT EXISTS LOGIN (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    "characterId" INT NOT NULL,
    "YEAR" INT NOT NULL,
    "MONTH" INT NOT NULL,
    "COUNT" INT NOT NULL
);

ALTER TABLE LOGIN ADD CONSTRAINT LOGIN_CHARACTERID_YEAR_MONTH_UNIQUE UNIQUE ("characterId", "YEAR", "MONTH");
